version: '2'
services:

    dycast:
      container_name: dycast
      restart: always
      image: cvast/cvast-dycast:2.0.1dev
      build:
        context: .
        dockerfile: ./Dockerfile
      command: bash -c  "sleep 10 && /docker/entrypoint.sh"
      environment:
        - MONTE_CARLO_FILE=/dycast/application/init/Zika_max_75.csv
        - SPATIAL_DOMAIN=
        - TEMPORAL_DOMAIN=
        - CLOSE_SPACE=
        - CLOSE_TIME=
        - CASE_THRESHOLD=
        - START_DATE=
        - END_DATE=
        - SRID_CASES=3857
        - SRID_EXTENT=3857
        - EXTENT_MIN_X=
        - EXTENT_MIN_Y=
        - EXTENT_MAX_X=
        - EXTENT_MAX_Y=
        - DEBUG=False
        - WAIT_FOR_ATTACH=False
        - DBPASSWORD=postgres
        - DBINSTANCE_NAME=dycast
        - DBHOST=dycast-db
        - DBPORT=5432
        - TZ=EST
      depends_on:
        - dycast-db

    dycast-db:
      container_name: dycast-db
      restart: always
      image: mdillon/postgis:9.6
      volumes:
          - dycast-postgres-data:/var/lib/postgresql/data
          - dycast-postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - TZ=EST


volumes:
    dycast-postgres-data:
    dycast-postgres-log:
