version: '2'
services:

    zikast:
      container_name: zikast
      restart: always
      image: cvast/cvast-zikast:2.0.1dev
      build:
        context: .
        dockerfile: ./Dockerfile
      command: bash -c  "sleep 10 && /docker/entrypoint.sh"
      environment:
        - FORCE_DB_INIT=False
        - START_DATE=
        - END_DATE=
        - USER_COORDINATE_SYSTEM=
        - EXTENT_MIN_X=
        - EXTENT_MIN_Y=
        - EXTENT_MAX_X=
        - EXTENT_MAX_Y=
        - DEBUG=False
        - REMOTE_DEBUG=False
        - PGPASSWORD=postgres
        - PGDBNAME=zikast
        - PGHOST=zikast-db
        - PGPORT=5432
        - TZ=EST
      depends_on:
        - zikast-db

    zikast-db:
      container_name: zikast-db
      restart: always
      image: mdillon/postgis:9.6
      volumes:
          - zikast-postgres-data:/var/lib/postgresql/data
          - zikast-postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - TZ=EST


volumes:
    zikast-postgres-data:
    zikast-postgres-log:
