version: '2'
services:

    zikast:
      container_name: zikast
      restart: always
      image: cvast/cvast-zikast:dev
      build: 
        context: .
        dockerfile: ./Dockerfile
      command: bash -c  "sleep 10 && /docker/entrypoint.sh"
      environment:
        - FORCE_DB_INIT=False
        - START_DATE=
        - END_DATE=
        - DEBUG=False
        - PGPASSWORD=postgres
        - PGDBNAME=zikast
        - PGHOST=zikast-db
        - PGPORT=5432
        - TZ=EST
      ports:
        - '81:8000'
      depends_on:
        - zikast-db
        
    zikast-db:
      container_name: zikast-db
      restart: always
      image: jthibault/postgis:latest
      volumes:
          - zikast-postgres-data:/var/lib/postgresql/data
          - zikast-postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - TZ=EST
    
        
volumes:
    zikast-postgres-data:
    zikast-postgres-log: