"""empty message

Revision ID: 5f1d828c113c
Revises: 49c435ef88a3
Create Date: 2021-04-24 09:35:25.265486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1d828c113c'
down_revision = '49c435ef88a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distribution_margins', 'probability', type_=sa.Integer())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distribution_margins', 'probability', type_=sa.Float())
    # ### end Alembic commands ###
